# Generated by Django 4.2.13 on 2024-09-10 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartItems', to='main.clientcard')),
                ('service', models.ManyToManyField(to='main.service')),
            ],
            options={
                'verbose_name': 'ShopCart',
                'verbose_name_plural': 'ShopCarts',
            },
        ),
    ]
