# Generated by Django 4.2.13 on 2024-09-14 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_shopcart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcard',
            name='diagnoses',
            field=models.ManyToManyField(blank=True, to='main.diagnosis'),
        ),
        migrations.AlterField(
            model_name='clientcard',
            name='doctors',
            field=models.ManyToManyField(blank=True, related_name='client', to='main.doctor'),
        ),
    ]
