# Generated by Django 4.2.13 on 2024-09-14 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_clientcard_diagnoses_alter_clientcard_doctors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopcart',
            name='service',
        ),
        migrations.AddField(
            model_name='shopcart',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shopCarts', to='main.service'),
        ),
    ]
