# Generated by Django 4.2.13 on 2024-09-14 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
