# Generated by Django 4.2.13 on 2024-09-14 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_history_prop_about_certificate_about_logourl_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='logoUrl',
        ),
    ]
